### PR TITLE
add some tweaks for more recent numpy

### PR DESCRIPTION
**Pull request by floe**
One more: on my default install, numpy 1.13.3 requires me to explicitly cast to int in some locations. Not sure if this is globally required, though.

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks, @floe!  It may also be worth noting that a lot of this code has been ported to https://scikit-image.org, so it's worth checking if something is available there before using it from here (scikit-image has, by now, been much more thoroughly reviewed).

**Comment by floe** [comment]
Thanks - yes, I know about scikit-image, but I haven't been able to find the corresponding functions in the API reference, so I gave SupReMe a try first.

**Comment by stefanv** [comment]
Interesting. Which functionality do you need most?

**Comment by floe** [comment]
I was looking for the polygon-based superresolution algorithm...

**Comment by stefanv** [comment]
I see! Then you are at the right place.  Let me know if I can help.

**Pull request merged**
